import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Fully autogenerated sidebar: any doc added under `docs/` by any
 * contributor shows up automatically. Ordering within a directory is
 * controlled by `sidebar_position` front matter / `_category_.json`
 * files in the docs themselves.
 */
const sidebars: SidebarsConfig = {
  courseSidebar: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
};

export default sidebars;
